# Generated by Django 3.2 on 2023-02-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_unique_author_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_author_review',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_review'),
        ),
    ]
